### ISSUE TITLE
Graphic.to_Image() doesn't support transparency

### ISSUE THREAD

**Issue by jmickle66666666** [devinacker/omgifol#17]
https://github.com/devinacker/omgifol/blob/master/lump.py#L165

The format for the image used ("P") does not support transparency, and any transparent pixels in a graphic are rendered at RGB(255,0,255). This means not only will all exported sprites/patches contain magenta areas, when building textures from patches, every patch with a transparent area will put magenta pixels over the texture. 

Example: https://puu.sh/uUJAa/3c86248001.png

A (computationally slow) workaround is possible currently with the following code:
```
patch_img = wad.patches[patch_name].to_Image()
patch_img = patch_img.convert("RGBA") # Convert to a format that supports alpha transparency

pixdata = patch_img.load()
width, height = patch_img.size
for y in xrange(height):
  for x in xrange(width):
    if pixdata[x, y] == (255, 0, 255, 255): # Find any magenta pixels
      pixdata[x, y] = (255, 255, 255, 0) # Replace with transparent pixel
```
This adds a significant amount of time to loading patches, especially when working with entire wads of textures such as the IWADs.

**Comment by devinacker** [comment]
what I might do instead:

* add some way to generate a 1-bit alpha mask for an image
* extend to_Image to allow specifying a pixel format and applying the mask if possible (i.e. RGBA)

Mask generation would probably also help for compositing patches to build textures, per the other issue

**Comment by devinacker** [comment]
Graphic.to_Image now has an optional mode parameter; passing "RGBA" produces an image with transparency.

There are also now to_pixels and from_pixels, which deal in lists of 8-bit pixel values with transparent pixels as negative. These might be usable for converting whole textures to 8-bit images or if converting and pasting a bunch of smaller RGBA images together doesn't perform well.
