### ISSUE TITLE
mirror.py demo script has issues saving certain maps

### ISSUE THREAD

**Issue by SteelT1** [devinacker/omgifol#26]
When attempting to save a map to the wad, it would error out with 
```Traceback (most recent call last):
  File "mirror.py", line 40, in <module>
    if __name__ == "__main__": main(argv[1:])
  File "mirror.py", line 38, in main
    outwad.to_file(args[1])
  File "/usr/lib/python3.6/site-packages/omg/wad.py", line 275, in to_file
    self.__dict__[group].save_wadio(w)
  File "/usr/lib/python3.6/site-packages/omg/wad.py", line 138, in save_wadio
    wadio.insert(t, hs[t].data)
AttributeError: 'list' object has no attribute 'data'
```

**Comment by devinacker** [comment]
Seems to affect maps with missing or unsupported nodes. Can you update/apply 50b5988d730153d962501f945625dbb33c02a33e and see if that fixes it for you?

**Comment by SteelT1** [comment]
Now it has problems attempting to read the file header. 
```
File "test.wad", line 1
    PWAD.
         ^
SyntaxError: invalid syntax
```

**Comment by devinacker** [comment]
Er, are you sure you actually ran the script and not just "`python test.wad`" or something?

**Comment by SteelT1** [comment]
Huh, I thought I did, anyways, after actually running the script, it actually saved the wad sucessfully, so the changes made fixed it!

**Comment by devinacker** [comment]
👍
