### ISSUE TITLE
ACS script is not written into the new wad file

### ISSUE THREAD

**Issue by TianyuanYu** [devinacker/omgifol#28]
@devinacker 

I see why this  #27  happens. The acs script is not written into the new wad file. The data is stored in map_editor.scripts.data. 

I have tried using the demo/mirror.py to verify this. And it may be the reason why the impassable walls can be passed  through.

Could you fix this? Thanks in advance.

**Comment by TianyuanYu** [comment]
I have revised from SCRIPT* to SCRIPTS in _maptail of wad.py. The scripts has been written into the wad file. However, the wall still can be passed through...

**Comment by TianyuanYu** [comment]
I also tried using copy() to copy a linedef from the original impassable wall. But once the vx_a and vx_b are changed, the new wall can be passed through. lol

**Comment by devinacker** [comment]
Should be fixed in 6be805a now. Also I responded to #27 with the real reason for the non-solid lines.
