### ISSUE TITLE
inconsistent api for creating lumps from various classes

### ISSUE THREAD

**Issue by jmickle66666666** [devinacker/omgifol#32]
To create a PLAYPAL lump, the process is:

```pal = omg.palette.Palette()
pal.make_bytes()
lump = omg.Lump(pal.bytes)
```

To create a COLORMAP lump, the process is:
```col = omg.colormap.Colormap()
lump = col.to_lump()
```

The API should be consistent when dealing with different types of data. I think the to_lump() function should be available on the Palette class since that is consistent with most of the rest of the API (to_file, to_Image etc)

**Comment by devinacker** [comment]
The Palette class is just for a single palette (which PLAYPAL contains 14 of); the related Playpal class already has to_lump. Not sure if there are any other classes that are missing a to_lump(s) method...

**Comment by jmickle66666666** [comment]
oh right! that makes more sense (I missed that Playpal existed)

the only other inconsistency is that a lot of the classes inherit from Lump (Graphic, Flat, Sound), while  
Colormap and Playpal don't?

**Comment by devinacker** [comment]
All the classes with to_lump(s) are "editor" classes, which are supposed to represent stuff in a more abstract way than just the underlying binary data (i.e. map stuff, palette RGB colors, etc).

(Also now that I'm thinking about it, I wonder if the Playpal class should support the extended Hexen playpal and maybe also other editor classes for the Heretic/Hexen/Strife tinttab and xlatab)
