### ISSUE TITLE
This branch no longer works on Python 2.4

### ISSUE THREAD

**Issue by linguica** [devinacker/omgifol#7]
I replaced my old omgifol scripts with these and under Python 2.4.4 they no longer worked properly. "from omg import *" threw up errors.

If it now requires Python 2.7 please update the docs to say so.

**Comment by devinacker** [comment]
I haven't used anything older than 2.7 in long enough to remember what I or anyone else might have added that broke that support, but I don't think there's any reason not to be using 2.7 (if not 3.x) at this point. Noted in the readme anyway.
